# General {{{
set -g default-shell $SHELL 
set-option -s escape-time 0

set-option -g prefix C-t
bind C-t send-prefix
unbind C-b

# reload tmux.conf
bind r source-file ~/.tmux.conf \; display-message "Reload Config!!"

# default open current directory
bind c new-window -c "#{pane_current_path}"
bind % split-window -hc "#{pane_current_path}"
bind '"' split-window -vc "#{pane_current_path}"

# vim <=> tmux 間でクリップボード利用を可能にする
set -g default-command "reattach-to-user-namespace -l ${SHELL}"
#set-option -g default-command "reattach-to-user-namespace -l $SHELL"

# ステータスバーをトップに配置する
set-option -g status-position top

# 左右のステータスバーの長さを決定する
set-option -g status-left-length 90
set-option -g status-right-length 90

# #H => マシン名
# #P => ペイン番号
# 最左に表示
set-option -g status-left '#H:[#P]'

# 現在時刻
# 最右に表示
set-option -g status-right '[%Y-%m-%d(%a) %H:%M]'

# ステータスバーを1秒毎に描画し直す
set-option -g status-interval 1

# センタライズ（主にウィンドウ番号など）
set-option -g status-justify centre

# Vi キーバインド
set-window-option -g mode-keys vi

# Prefix+v でコピーモード開始
bind-key v copy-mode \; display "Copy mode!"
#bind-key -t vi-copy v begin-selection

# Prefix+Enter/y でコピー
bind-key -t vi-copy Enter copy-pipe "reattach-to-user-namespace pbcopy"
bind-key -t vi-copy y     copy-pipe "reattach-to-user-namespace pbcopy"

# Prefix+p でペースト
# クリップボードにも保存されているので Cmd-v でもペースト可能
bind-key p paste-buffer

# Esc キーでコピーの反転を解除（コピーモードは抜けない）
bind-key -t vi-copy Escape clear-selection
# Ctrl-c キーでコピーの反転を解除し、コピーモードから抜ける
bind-key -t vi-copy C-c cancel

# コピーモード中（Prefix+v 後）C-v で矩形選択開始
bind-key -t vi-copy C-v rectangle-toggle
# 1行選択
bind-key -t vi-copy V select-line

# 単語の最初の1文字に移動
bind-key -t vi-copy w next-word
# 単語の最後の1文字に移動
bind-key -t vi-copy e next-word-end
# w の逆の動き back
bind-key -t vi-copy b previous-word

# 画面上に映る最上行に移動
bind-key -t vi-copy g top-line
# 画面上に映る最下行に移動
bind-key -t vi-copy G bottom-line

# 前方検索
bind-key -t vi-copy / search-forward
# 後方検索
bind-key -t vi-copy ? search-backward

# ページスクロール
bind-key -t vi-copy C-n page-up
bind-key -t vi-copy C-f page-down

# ページ送り
bind-key -t vi-copy C-u scroll-up
bind-key -t vi-copy C-d scroll-down

# ウィンドウとペインの番号を1から開始する（デフォルト0）
set-option -g base-index 1
set-window-option -g pane-base-index 1

# Prefix+- で横に、Prefix+| で縦に分割（ペイン）する
bind-key | split-window -h
bind-key - split-window -v

# Prefix + Ctrl-h/l でウィンドウ切り替え
# Prefix + Ctrl-h,h,h,h,...と連打できる
bind-key -r C-h select-window -t :-
bind-key -r C-l select-window -t :+

# Prefix+hjkl でペイン移動
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# ペインサイズを上下左右（Prefix+JKHL）に変更
# Prefix+J,J,J,J,...と連打してリサイズ可能
bind-key -r H resize-pane -L 5
bind-key -r J resize-pane -D 5
bind-key -r K resize-pane -U 5
bind-key -r L resize-pane -R 5

##################
# color
##################


# default statusbar colors
set-option -g status-bg colour243
set-option -g status-fg colour236
set-option -g status-attr default

# default window title colors
set-window-option -g window-status-fg colour237 #base0
set-window-option -g window-status-bg default
set-window-option -g window-status-attr dim

# active window title colors
set-window-option -g window-status-current-fg colour18
set-window-option -g window-status-current-bg default
#set-window-option -g window-status-current-attr bright

# pane border
# set-option -g pane-border-fg colour235 #base02
# set-option -g pane-active-border-fg colour240 #base01
set -g pane-active-border-fg colour244
set -g pane-active-border-bg colour244
set -g pane-border-fg colour243
set -g pane-border-bg colour243

# message text
set-option -g message-bg colour235 #base02
set-option -g message-fg colour166 #orange

# pane number display
set-option -g display-panes-active-colour colour33 #blue
set-option -g display-panes-colour colour166 #orange

# clock
set-window-option -g clock-mode-colour colour64 #green
