# General {{{
set -g default-shell $SHELL 
set-option -s escape-time 0

set-option -g prefix C-t
bind C-t send-prefix
unbind C-b

# reload tmux.conf
bind r source-file ~/.tmux.conf \; display-message "Reload Config!!"

# default open current directory
bind c new-window -c "#{pane_current_path}"
bind % split-window -hc "#{pane_current_path}"
bind '"' split-window -vc "#{pane_current_path}"

# vim <=> tmux 間でクリップボード利用を可能にする
set-option -g default-command "reattach-to-user-namespace -l $SHELL"

# Vi キーバインド
set-window-option -g mode-keys vi

# Prefix+v でコピーモード開始
bind-key v copy-mode \; display "Copy mode!"

# Prefix+Enter/y でコピー
bind-key -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "reattach-to-user-namespace pbcopy"
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "reattach-to-user-namespace pbcopy"


# Prefix+p でペースト
# クリップボードにも保存されているので Cmd-v でもペースト可能
bind-key p paste-buffer

# Esc キーでコピーの反転を解除（コピーモードは抜けない）
bind-key -T copy-mode-vi Escape send-keys -X clear-selection
# Ctrl-c キーでコピーの反転を解除し、コピーモードから抜ける
bind-key -T copy-mode-vi C-c send-keys -X cancel

# コピーモード中（Prefix+v 後）C-v で矩形選択開始
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
# 1行選択
bind-key -T copy-mode-vi V send-keys -X select-line

# 単語の最初の1文字に移動
bind-key -T copy-mode-vi w send-keys -X next-word
# 単語の最後の1文字に移動
bind-key -T copy-mode-vi e send-keys -X next-word-end
# w の逆の動き back
bind-key -T copy-mode-vi b send-keys -X previous-word

# 画面上に映る最上行に移動
bind-key -T copy-mode-vi g send-keys -X top-line
# 画面上に映る最下行に移動
bind-key -T copy-mode-vi G send-keys -X bottom-line

# 前方検索
bind-key -T copy-mode-vi / send-keys -X search-forward
# 後方検索
bind-key -T copy-mode-vi ? send-keys -X search-backward

# ページスクロール
bind-key -T copy-mode-vi C-n send-keys -X page-up
bind-key -T copy-mode-vi C-f send-keys -X page-down

# ページ送り
bind-key -T copy-mode-vi C-u send-keys -X scroll-up
bind-key -T copy-mode-vi C-d send-keys -X scroll-down

# ウィンドウとペインの番号を1から開始する（デフォルト0）
set-option -g base-index 1
set-window-option -g pane-base-index 1

# Prefix+- で横に、Prefix+| で縦に分割（ペイン）する
bind-key | split-window -h
bind-key - split-window -v

# Prefix+hjkl でペイン移動
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# ペインサイズを上下左右（Prefix+JKHL）に変更
# Prefix+J,J,J,J,...と連打してリサイズ可能
bind-key -r H resize-pane -L 5
bind-key -r J resize-pane -D 5
bind-key -r K resize-pane -U 5
bind-key -r L resize-pane -R 5


##################
# status bar
##################
# ステータスバーをトップに配置する
set-option -g status-position bottom

# # 左右のステータスバーの長さを決定する
# set-option -g status-left-length 90
# set-option -g status-right-length 90

# # #H => マシン名
# # #P => ペイン番号
# # 最左に表示
# set-option -g status-left '#H:[#P]'

# # 現在時刻
# # 最右に表示
# set-option -g status-right '[%Y-%m-%d(%a) %H:%M]'

# # ステータスバーを1秒毎に描画し直す
# set-option -g status-interval 1

# # センタライズ（主にウィンドウ番号など）
# set-option -g status-justify centre

##################
# color
##################

set-window-option -g window-status-fg colour237 #base0
set-window-option -g window-status-bg default
set-window-option -g window-status-attr dim

# active window title colors
set-window-option -g window-status-current-fg colour64
set-window-option -g window-status-current-bg default
set-window-option -g window-status-fg white
set-option -g status-bg colour236
set-option -g status-fg white

# pane border
set -g pane-border-fg colour234
set -g pane-border-bg black
set -g pane-active-border-fg colour23
set -g pane-active-border-bg colour23

# message text
set-option -g message-bg colour235 #base02
set-option -g message-fg colour166 #orange

# pane number display
set-option -g display-panes-active-colour colour33 #blue
set-option -g display-panes-colour colour166 #orange

# clock
# set-window-option -g clock-mode-colour colour64 #green
