[[plugins]]
    repo = 'Shougo/dein.vim'

[[plugins]]
    repo = 'Shougo/deoplete.nvim'
    on_i = 1
    hook_add = '''
        inoremap <expr><TAB>  pumvisible() ? "\<C-n>" : "\<TAB>"
        inoremap <expr><S-TAB>  pumvisible() ? "\<C-p>" : "\<S-TAB>" 
    '''

[[plugins]]
    repo = 'Shougo/unite.vim'
    hook_add = '''
        let g:unite_enable_start_insert=1
        nnoremap <silent> <space>ub :<C-u>Unite buffer<CR>
        nnoremap <silent> <space>uf :<C-u>UniteWithBufferDir -buffer-name=files file<CR>
        nnoremap <silent> <space>ur :<C-u>Unite -buffer-name=register register<CR>
    '''

[[plugins]]
    repo = 'Shougo/neoyank.vim'
    hook_add = '''
        nnoremap <silent> <space>uy :<C-u>Unite history/yank<CR>
    '''
[[plugins]]
    repo = 'Shougo/neopairs.vim'
    hook_add = '''
        let g:neopairs#enable = 1
    '''

[[plugins]]
    repo = 'Shougo/vimproc.vim'
    build = 'make'

[[plugins]]
    repo = 'Shougo/vimshell'
    hook_add = '''
        nnoremap <silent> <space>vs :<C-u>VimShell<CR>
        nnoremap <silent> <space>vp :<C-u>VimShellPop<CR>
        autocmd FileType vimshell imap 
            \ <buffer><silent><expr><C-d>
            \ vimshell#get_cur_text()=='' ? "\<Esc>\<Plug>(vimshell_exit)" : "\<Del>"
    '''
[[plugins]]
    repo = 'itchyny/lightline.vim'
    #lightline settings{{{
    hook_add = '''
        set laststatus=2
        if !has('gui_running')
            set t_Co=256
        endif

        let g:lightline = {
        \ 'colorscheme': 'wombat',
        \ 'mode_map': {'c': 'NORMAL'},
        \ 'active': {
        \   'left': [ [ 'mode', 'paste' ], [ 'fugitive', 'filename' ] ]
        \ },
        \ 'component_function': {
        \   'modified': 'LightLineModified',
        \   'readonly': 'LightLineReadonly',
        \   'fugitive': 'LightLineFugitive',
        \   'filename': 'LightLineFilename',
        \   'fileformat': 'LightLineFileformat',
        \   'filetype': 'LightLineFiletype',
        \   'fileencoding': 'LightLineFileencoding',
        \   'mode': 'LightLineMode'
        \ } ,
        \ 'component_expand': {
        \   'syntastic': 'SyntasticStatuslineFlag'
        \ },
        \ 'component_type': {
        \   'syntastic': 'error'
        \ }
        \ }

        let g:lightline.component_expand = {
        \ 'tabs': 'lightline#tabs' } 
        let g:lightline.component_type = {
        \ 'tabs': 'tabsel' } 

        let g:syntastic_mode_map = { 'mode': 'passive' }
        augroup AutoSyntastic
          autocmd!
          autocmd BufWritePost *.c,*.cpp call s:syntastic()
        augroup END
        function! s:syntastic()
          SyntasticCheck
          call lightline#update()
        endfunction

        function! LightLineModified()
          return &ft =~ 'help\|vimfiler\|gundo' ? '' : &modified ? '+' : &modifiable ? '' : '-'
        endfunction

        function! LightLineReadonly()
          return &ft !~? 'help\|vimfiler\|gundo' && &readonly ? 'x' : ''
        endfunction

        function! LightLineFilename()
          return ('' != LightLineReadonly() ? LightLineReadonly() . ' ' : '') .
                \ (&ft == 'vimfiler' ? vimfiler#get_status_string() :
                \  &ft == 'unite' ? unite#get_status_string() :
                \  &ft == 'vimshell' ? vimshell#get_status_string() :
                \ '' != expand('%:t') ? expand('%:t') : '[No Name]') .
                \ ('' != LightLineModified() ? ' ' . LightLineModified() : '')
        endfunction

        function! LightLineFugitive()
          try
            if &ft !~? 'vimfiler\|gundo' && exists('*fugitive#head')
              return fugitive#head()
            endif
          catch
          endtry
          return ''
        endfunction

        function! LightLineFileformat()
          return winwidth(0) > 70 ? &fileformat : ''
        endfunction

        function! LightLineFiletype()
          return winwidth(0) > 70 ? (strlen(&filetype) ? &filetype : 'no ft') : ''
        endfunction

        function! LightLineFileencoding()
          return winwidth(0) > 70 ? (strlen(&fenc) ? &fenc : &enc) : ''
        endfunction

        function! LightLineMode() 
            return winwidth(0) > 60 ? lightline#mode() : ''
        endfunction
    '''
#}}}

[[plugins]]
    repo = 'Shougo/neosnippet'

[[plugins]]
    repo = 'Shougo/neosnippet-snippets'

[[plugins]]
    repo = 'othree/html5.vim'

[[plugins]]
    repo = 'tpope/vim-surround'

[[plugins]]
    repo = 'thinca/vim-quickrun'
    hook_add = '''
        nnoremap = <silent> <space>qr :<C-u>QuickRun<CR>
    '''

[[plugins]]
    repo = 'cohama/lexima.vim'
    on_i = '''
        call lexima#add_rule({'char': '$', 'input_after': '$', 'filetype': 'latex'})
        call lexima#add_rule({'char': '$', 'at': '\%#\$', 'leave': 1, 'filetype': 'latex'})
        call lexima#add_rule({'char': '<BS>', 'at': '\$\%#\$', 'delete': 1, 'filetype': 'latex'})
    '''

[[plugins]]
    repo = 'tpope/vim-fugitive'
    hook_add = '''
        nnoremap <silent> <space>gs :<C-u>Gstatus<CR>
        nnoremap <silent> <space>gc :<C-u>Gcommit<CR>
        nnoremap <silent> <space>ga :<C-u>Gwrite<CR>
        nnoremap <silent> <space>gd :<C-u>Gdiff<CR>
        nnoremap <silent> <space>gb :<C-u>Gblame<CR>
    '''

[[plugins]]
    repo = 'airblade/vim-gitgutter'
    hook_add = '''
        let g:gitgutter_sign_added = '✚'
        let g:gitgutter_sign_modified = '➜'
        let g:gitgutter_sign_removed = '✘'
    '''
[[plugins]]
    repo = 'plasticboy/vim-markdown'

[[plugins]]
    repo = 'pangloss/vim-javascript'

[[plugins]]
    repo = 'scrooloose/syntastic'
    hook_add = '''
        let g:syntastic_enable_signs=1
        let g:syntastic_auto_loc_list=2
    '''

[[plugins]]
    repo = 'easymotion/vim-easymotion'
    hook_add = '''
        "easymotion settings
        " =======================================
        " boost your productivity with easymotion
        " =======================================
        " disable default mappings
        " if you are true vimmer, you should explicitly map keys by yourself.
        " do not rely on default bidings.
        let g:easymotion_do_mapping = 0
        " or map prefix key at least(default: <leader><leader>)
        " map <leader> <plug>(easymotion-prefix)
        " =======================================
        " find motions
        " =======================================
        " jump to anywhere you want by just `4` or `3` key strokes without thinking!
        " `s{char}{char}{target}`
        nmap s <plug>(easymotion-s2)
        xmap s <plug>(easymotion-s2)
        omap z <plug>(easymotion-s2)
        " of course, you can map to any key you want such as `<space>`
        " map <space>(easymotion-s2)
        " " turn on case sensitive feature
        let g:easymotion_smartcase = 1
        " =======================================
        " line motions
        " =======================================
        " `jk` motions: extend line motions
        map <leader>j <plug>(easymotion-j)
        map <leader>k <plug>(easymotion-k)
        " keep cursor column with `jk` motions
        let g:easymotion_startofline = 0
        " =======================================
        " general configuration
        " =======================================
        let g:easymotion_keys = ';hklyuiopnm,qwertasdgzxcvbjf'
        " show target key with upper case to improve readability
        let g:easymotion_use_upper = 1
        " jump to first match with enter & space
        let g:easymotion_enter_jump_first = 1
        let g:easymotion_space_jump_first = 1
    '''

[[plugins]]
    repo = 'tomasr/molokai'
    on_event = ['VimEnter']
    hook_add = '''
        set background=dark
        colorscheme molokai
'''
[[plugins]]
    repo = 'scrooloose/syntastic.git'

[[plugins]] # カーソル位置のコンテキストに合わせてftを切り替える
    repo = 'osyo-manga/vim-precious'
    depends = ['Shougo/context_filetype.vim']

[[plugins]] # カーソル位置のコンテキストのftを判定するライブラリ
    repo = 'Shougo/context_filetype.vim'

[[plugins]]
    repo = 'mattn/emmet-vim'
    on_ft = ['html']

[[plugins]] # toml syntax
    repo = 'cespare/vim-toml'
    on_ft = 'toml'

[[plugins]]
    repo = 'Shougo/vimfiler.vim'
    hook_add ='''
        nnoremap <space>vf :VimFilerExplorer<CR>
        " close vimfiler automatically when there are only vimfiler open
        autocmd MyAutoCmd BufEnter * if (winnr('$') == 1 && &filetype ==# 'vimfiler') | q | endif
          let g:vimfiler_as_default_explorer = 1
          let g:vimfiler_enable_auto_cd = 1
          
          " vimfiler specific key mappings
          autocmd MyAutoCmd FileType vimfiler call s:vimfiler_settings()
          function! s:vimfiler_settings()
            " ^^ to go up
            nmap <buffer> ^^ <Plug>(vimfiler_switch_to_parent_directory)
            " use R to refresh
            nmap <buffer> R <Plug>(vimfiler_redraw_screen)
            " overwrite C-l
            nmap <buffer> <C-l> <C-w>l
          endfunction
    '''

[[plugins]]
    repo = 'kakkyz81/evervim'

[[plugins]]
    repo = 'tyru/open-browser.vim'

[[plugins]]
    repo = 'kannokanno/previm'

#Ruby Settings
[[plugins]]
    repo = 'vim-ruby/vim-ruby'
    on_ft = ['ruby']

[[plugins]]
    repo = 'osyo-manga/vim-monster'

#python settings
[[plugins]]
    repo = 'davidhalter/jedi-vim'
    on_ft = ['python', 'python3', 'djangohtml']

#NyaoVim Settings
[[plugins]]
    repo = 'rhysd/nyaovim-markdown-preview'

[[plugins]]
    repo = 'rhysd/nyaovim-mini-browser'

